title: Jekyll Base
description: >- # this means to ignore newlines until "baseurl:"
  Just a reminder that nothing lasts forever.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

source: src
destination: ../_site


defaults:
  - scope:
      path: "pages/index.md"
    values:
      permalink: '/'

sass:
    sass_dir: _sass

excerpt_separator: <!--more-->

exclude:
  - scripts
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn-error.log
  - yarn.lock
  - node_modules